// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"common/db/query"
	"user/internal/infra/db"
	"user/internal/interface/graphql/resolver"
	"user/internal/service"
)

// Injectors from wire.go:

func InitializeResolver(query2 *query.Query) *resolver.Resolver {
	userRepository := db.NewUserRepository(query2)
	userService := service.NewUserService(userRepository)
	resolverResolver := resolver.NewResolver(userService)
	return resolverResolver
}
