services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecpark
      MYSQL_USER: tecpark
      MYSQL_PASSWORD: tecpark
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 23306:3306
    healthcheck:
      test: mysqladmin ping -proot
    networks:
      - service

  backend:
    build: backend
    image: backend:latest

  user:
    build:
      context: backend/user
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tecpark
      MYSQL_USER: tecpark
      MYSQL_PASSWORD: tecpark
    ports:
      - 8080:80
    depends_on:
      backend:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    networks:
      - service

  migrate:
    build:
      context: backend/db/mysql/schema
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tecpark
      MYSQL_USER: tecpark
      MYSQL_PASSWORD: tecpark
    depends_on:
      backend:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    networks:
      - service

volumes:
  mysql_data:

networks:
  service:
