services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/rdb/my.cnf:/etc/mysql/my.cnf
    ports:
      - 23306:3306
    healthcheck:
      test: mysqladmin ping -proot
    networks:
      - service

  test_mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    volumes:
      - ./backend/db/rdb/my.cnf:/etc/mysql/my.cnf
    ports:
      - 33306:3306
    healthcheck:
      test: mysqladmin ping -proot

  backend:
    build: backend
    image: backend:latest

  user:
    build:
      context: backend/api/user
      dockerfile_inline: |
        FROM backend:latest
        WORKDIR /app/backend/api/user
        RUN go mod download
        RUN go install github.com/air-verse/air@latest
        EXPOSE 80
        CMD [ "air" ]
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tecpark
      MYSQL_USER: tecpark
      MYSQL_PASSWORD: tecpark
    volumes:
      - ./backend:/app/backend
    ports:
      - 8080:80
    depends_on:
      backend:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    networks:
      - service

  migrate:
    build:
      context: backend/db/rdb/schema
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tecpark
      MYSQL_USER: tecpark
      MYSQL_PASSWORD: tecpark
    depends_on:
      backend:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    networks:
      - service

volumes:
  mysql_data:

networks:
  service:
