services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecpark
      MYSQL_USER: tecpark
      MYSQL_PASSWORD: tecpark
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 23306:3306
    healthcheck:
      test: mysqladmin ping -proot
    networks:
      - db

  migrate:
    image: arigaio/atlas:latest
    command: migrate apply --url mysql://tecpark:tecpark@mysql:3306/tecpark
    volumes:
      - ./db/mysql/migrations/:/migrations
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - db

volumes:
  mysql_data:

networks:
  db:
