version: '3'

tasks:
  setup:
    cmd: docker compose up -d
  
  down:
    cmd: docker compose down --volumes --rmi local

  mysql-login:
    cmd: docker compose exec mysql mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h 127.0.0.1 ${MYSQL_DATABASE}
