[tasks."schema:inspect"]
run = "atlas schema inspect --env local > schema/schema.hcl"

[tasks."schema:apply"]
run = "atlas schema apply --env local"

[tasks."migrate:diff"]
run = "atlas migrate diff --env gorm"

[tasks."migrate:apply"]
run = "atlas migrate apply --env local"

[tasks.query]
run = "go run main.go"
dir = "cmd/query"

[tasks.migrate]
run = "go run main.go"
dir = "cmd/migrate"
