version: "2"

linters:
  default: all

  disable:
    - varnamelen #変数名は短い場合もあるため

  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true #パッケージにコメントは必要ないため
    paralleltest:
      ignore-missing: true #testifyではスイート単位で並列実行しない
    ireturn:
      allow:
        - error
        - .*/repository\.
        - Resolver$
    gosmopolitan:
      allow-time-local: true

  exclusions:
    rules:
      - path: main\.go
        linters:
          - exhaustruct
      - path: _test\.go
        linters:
          - exhaustruct
      - path: export_test\.go
        linters:
          - gochecknoglobals
