// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"user/internal/infra/db"
	"user/internal/interface/graphql/resolver"
	"user/internal/usecase"
)

// Injectors from wire.go:

func InitializeResolver(conn *gorm.DB) *resolver.Resolver {
	user := db.NewUser(conn)
	usecaseUser := usecase.NewUser(user)
	resolverResolver := resolver.NewResolver(usecaseUser)
	return resolverResolver
}
