name: "Set up Terragrunt"

inputs:
  env:
    required: true
    type: string
  tf_version:
    required: false
    type: string
    default: "1.9.5"
  tg_version:
    required: false
    type: string
    default: "0.66.9"

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf_version }}

    - name: Set up Terragrunt
      run: |
        sudo curl -sSL https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.tg_version }}/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
        sudo chmod +x /usr/local/bin/terragrunt
        terragrunt --version

    - name: Configure Terraform variables
      run: |
        echo "TF_VAR_terragrunt_env=${{ inputs.env }}" >> $GITHUB_ENV
        echo "TF_VAR_terragrunt_github_token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        echo "TF_VAR_terragrunt_github_owner=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_ENV
