name: 新規タスク
description: 機能追加や改善要望など
projects:
  - "takaaki12353491/11"
assignees:
  - "takaaki12353491"
body:
  - type: textarea
    id: user-story
    attributes:
      label: ユーザーストーリー
      description: ペルソナ、目標、理由を埋めてください。
      value: "[ペルソナ]として、[目標]したい。それは、[理由]からだ。"
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: 概要
    validations:
      required: true
  - type: dropdown
    id: velocity
    attributes:
      label: ベロシティ
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "21"
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: DoD
      description: チェックボックス形式にしてください。
    validations:
      required: true  
  - type: textarea
    id: other
    attributes:
      label: その他
    validations:
      required: false