package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	graphql2 "user/internal/adapter/graphql"
	model1 "user/internal/domain/model"

	xerrors "github.com/takaaki12353491/tecpark/backend/common/errors"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model1.User, error) {
	users, err := r.userIPort.GetUsers(ctx)
	if err != nil {
		return []*model1.User{}, xerrors.WithStack(err)
	}

	return users, nil
}

// Query returns graphql2.QueryResolver implementation.
func (r *Resolver) Query() graphql2.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
