name: Cherry-pick to Branch
description: Cherry-pick merged PR to target branch and create a new PR

inputs:
  target_branch:
    description: 'Target branch to cherry-pick to'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get merge commit SHA
      id: get-merge-commit
      shell: bash
      run: |
        MERGE_COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
        echo "merge_commit_sha=${MERGE_COMMIT_SHA}" >> $GITHUB_OUTPUT
        echo "Merge commit SHA: ${MERGE_COMMIT_SHA}"

    - name: Create cherry-pick branch
      id: create-branch
      shell: bash
      run: |
        TARGET_BRANCH="${{ inputs.target_branch }}"
        
        # ターゲットブランチの最新を取得
        git fetch origin "${TARGET_BRANCH}"

        # ブランチ名を生成（元のPRのブランチ名を使用）
        SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
        
        # ブランチ名から#以前の部分を削除（例: staging#feature/xxx -> feature/xxx）
        ORIGINAL_BRANCH="${SOURCE_BRANCH##*#}"
        
        # ユニークなブランチ名を生成
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        NEW_BRANCH="${TARGET_BRANCH}#${ORIGINAL_BRANCH}_${TIMESTAMP}"

        echo "new_branch=${NEW_BRANCH}" >> $GITHUB_OUTPUT
        echo "source_branch=${SOURCE_BRANCH}" >> $GITHUB_OUTPUT

        # ターゲットブランチから新しいブランチを作成
        git checkout -b "${NEW_BRANCH}" "origin/${TARGET_BRANCH}"
        echo "Created branch: ${NEW_BRANCH}"

    - name: Cherry-pick commits
      id: cherry-pick
      shell: bash
      run: |
        MERGE_COMMIT="${{ steps.get-merge-commit.outputs.merge_commit_sha }}"
        TARGET_BRANCH="${{ inputs.target_branch }}"

        echo "Cherry-picking commit: ${MERGE_COMMIT}"

        # チェリーピックを実行（cherry-pick 元の内容を優先しつつ、パイプの終了コードを正しく取得）
        set +e
        git cherry-pick -m 1 -X theirs "${MERGE_COMMIT}" 2>&1 | tee /tmp/cherry-pick-output.txt
        CHERRY_PICK_EXIT_CODE=${PIPESTATUS[0]}
        set -e

        echo "Cherry-pick exit code: ${CHERRY_PICK_EXIT_CODE}"

        if [ ${CHERRY_PICK_EXIT_CODE} -eq 0 ]; then
          echo "Cherry-pick successful"
          echo "success=true" >> $GITHUB_OUTPUT
          echo "is_empty=false" >> $GITHUB_OUTPUT
          echo "has_conflicts=false" >> $GITHUB_OUTPUT
        else
          # 空のコミット（変更が既に含まれている）かどうかを確認
          if grep -q "The previous cherry-pick is now empty" /tmp/cherry-pick-output.txt; then
            echo "Cherry-pick resulted in empty commit (changes already in ${TARGET_BRANCH})"
            echo "success=true" >> $GITHUB_OUTPUT
            echo "is_empty=true" >> $GITHUB_OUTPUT
            echo "has_conflicts=false" >> $GITHUB_OUTPUT
            git cherry-pick --skip
          else
            echo "Cherry-pick failed with conflicts - auto-resolving by taking cherry-pick source (theirs) side"

            # コンフリクトしているファイル一覧を取得
            CONFLICT_FILES=$(git diff --name-only --diff-filter=U || true)
            echo "Conflicted files:"
            echo "${CONFLICT_FILES}"

            if [ -n "${CONFLICT_FILES}" ]; then
              # 各コンフリクトファイルを cherry-pick 元（theirs 側）の内容で上書き
              for FILE in ${CONFLICT_FILES}; do
                [ -z "${FILE}" ] && continue
                git checkout --theirs -- "${FILE}"
                git add "${FILE}"
              done
            fi

            # 解消したファイル一覧を出力用に整形
            RESOLVED_FILES=$(echo "${CONFLICT_FILES}" | tr '\n' ',' | sed 's/,$//')

            # 解消した変更を確定
            GIT_EDITOR=true git cherry-pick --continue

            echo "success=true" >> $GITHUB_OUTPUT
            echo "is_empty=false" >> $GITHUB_OUTPUT
            echo "has_conflicts=true" >> $GITHUB_OUTPUT
            echo "resolved_files=${RESOLVED_FILES}" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Comment on empty commit
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = '${{ github.event.pull_request.number }}';
          const targetBranch = '${{ inputs.target_branch }}';

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: `ℹ️ ${targetBranch}ブランチへのチェリーピックをスキップしました。\n\nこの変更は既に${targetBranch}ブランチに含まれているため、チェリーピックの必要がありません。`
          });

    - name: Push branch
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'false'
      shell: bash
      run: |
        NEW_BRANCH="${{ steps.create-branch.outputs.new_branch }}"
        git push origin "${NEW_BRANCH}"
        echo "Pushed branch: ${NEW_BRANCH}"

    - name: Create Pull Request
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'false'
      id: create-pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = ${{ github.event.pull_request.number }};
          const prTitle = ${{ toJson(github.event.pull_request.title) }};
          const hasConflicts = '${{ steps.cherry-pick.outputs.has_conflicts }}' === 'true';
          const resolvedFiles = '${{ steps.cherry-pick.outputs.resolved_files }}';
          const targetBranch = '${{ inputs.target_branch }}';
          const newBranch = '${{ steps.create-branch.outputs.new_branch }}';

          const label = targetBranch.charAt(0).toUpperCase() + targetBranch.slice(1);
          // 元のタイトルから先頭の[]ラベルを削除
          const originalTitle = prTitle.replace(/^\[[^\]]+\]\s*/, '');

          // コンフリクトを自動解消した旨の注記(解消したファイル一覧付き)
          let conflictWarning = '';
          if (hasConflicts) {
            conflictWarning = `⚠️ コンフリクトを自動解消しました。\n\n解消したファイル一覧: ${resolvedFiles || '(取得できませんでした)'}`;
          }

          // 新しいPRのタイトル
          const newPRTitle = `[${label}] ${originalTitle}`;

          // 新しいPRの本文
          const bodyLines = [
            '### 元のPR',
            `- #${prNumber}`,
            '',
            conflictWarning,
            '',
            '---',
            '_このPRは GitHub Actions により自動生成されました_',
          ];
          const newPRBody = bodyLines.join('\n');

          // PRを作成
          const { data: newPR } = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: newPRTitle,
            head: newBranch,
            base: targetBranch,
            body: newPRBody,
          });

          core.setOutput('pr_number', String(newPR.number));
          core.setOutput('pr_url', newPR.html_url);

    - name: Comment on original PR
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = '${{ github.event.pull_request.number }}';
          const newPRNumber = '${{ steps.create-pr.outputs.pr_number }}';
          const hasConflicts = '${{ steps.cherry-pick.outputs.has_conflicts }}' === 'true';
          const targetBranch = '${{ inputs.target_branch }}';

          let message = '';
          if (hasConflicts) {
            message = `⚠️ ${targetBranch}ブランチへのチェリーピックPRが作成されました: #${newPRNumber}\n\n**注意**: コンフリクトを自動解消しました。PRを確認してください。`;
          } else {
            message = `✅ ${targetBranch}ブランチへのチェリーピックPRが作成されました: #${newPRNumber}`;
          }

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: message
          });

