name: Cherry-pick to Branch
description: Cherry-pick merged PR to target branch and create a new PR

inputs:
  target_branch:
    description: 'Target branch to cherry-pick to'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get merge commit SHA
      id: get-merge-commit
      shell: bash
      run: |
        MERGE_COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
        echo "merge_commit_sha=${MERGE_COMMIT_SHA}" >> $GITHUB_OUTPUT
        echo "Merge commit SHA: ${MERGE_COMMIT_SHA}"

    - name: Create cherry-pick branch
      id: create-branch
      shell: bash
      run: |
        TARGET_BRANCH="${{ inputs.target_branch }}"
        
        # ターゲットブランチの最新を取得
        git fetch origin "${TARGET_BRANCH}"

        # ブランチ名を生成（元のPRのブランチ名を使用）
        SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
        
        # ブランチ名から#以前の部分を削除（例: staging#feature/xxx -> feature/xxx）
        ORIGINAL_BRANCH="${SOURCE_BRANCH##*#}"
        
        NEW_BRANCH="${TARGET_BRANCH}#${ORIGINAL_BRANCH}"

        echo "new_branch=${NEW_BRANCH}" >> $GITHUB_OUTPUT
        echo "source_branch=${SOURCE_BRANCH}" >> $GITHUB_OUTPUT

        # ターゲットブランチから新しいブランチを作成
        git checkout -b "${NEW_BRANCH}" "origin/${TARGET_BRANCH}"
        echo "Created branch: ${NEW_BRANCH}"

    - name: Cherry-pick commits
      id: cherry-pick
      shell: bash
      run: |
        MERGE_COMMIT="${{ steps.get-merge-commit.outputs.merge_commit_sha }}"
        TARGET_BRANCH="${{ inputs.target_branch }}"

        echo "Cherry-picking commit: ${MERGE_COMMIT}"

        # チェリーピックを実行（パイプの終了コードを正しく取得）
        set +e
        git cherry-pick -m 1 "${MERGE_COMMIT}" 2>&1 | tee /tmp/cherry-pick-output.txt
        CHERRY_PICK_EXIT_CODE=${PIPESTATUS[0]}
        set -e

        echo "Cherry-pick exit code: ${CHERRY_PICK_EXIT_CODE}"

        if [ ${CHERRY_PICK_EXIT_CODE} -eq 0 ]; then
          echo "Cherry-pick successful"
          echo "success=true" >> $GITHUB_OUTPUT
          echo "is_empty=false" >> $GITHUB_OUTPUT
          echo "has_conflicts=false" >> $GITHUB_OUTPUT
        else
          # 空のコミット（変更が既に含まれている）かどうかを確認
          if grep -q "The previous cherry-pick is now empty" /tmp/cherry-pick-output.txt; then
            echo "Cherry-pick resulted in empty commit (changes already in ${TARGET_BRANCH})"
            echo "success=true" >> $GITHUB_OUTPUT
            echo "is_empty=true" >> $GITHUB_OUTPUT
            echo "has_conflicts=false" >> $GITHUB_OUTPUT
            git cherry-pick --skip
          else
            echo "Cherry-pick failed with conflicts"
            echo "success=true" >> $GITHUB_OUTPUT
            echo "is_empty=false" >> $GITHUB_OUTPUT
            echo "has_conflicts=true" >> $GITHUB_OUTPUT
            
            # コンフリクトが発生した場合の情報を記録
            git status > /tmp/conflict-status.txt
            echo "conflict_info<<EOF" >> $GITHUB_OUTPUT
            cat /tmp/conflict-status.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            # コンフリクトマーカー付きのファイルをステージング
            git add -A
            
            # cherry-pickの状態を確認してコミット
            if git rev-parse -q --verify CHERRY_PICK_HEAD > /dev/null; then
              # cherry-pickが進行中の場合、continueで完了させる
              GIT_EDITOR=true git cherry-pick --continue || true
            else
              # cherry-pickが中断されている場合、直接コミット
              git commit -m "Cherry-pick with conflicts from ${MERGE_COMMIT}" \
                -m "This commit contains unresolved conflicts from the original PR." \
                -m "Please resolve the conflicts manually before merging." \
                -m "Original commit: ${MERGE_COMMIT}" \
                --no-verify --allow-empty || true
            fi
          fi
        fi

    - name: Comment on empty commit
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = '${{ github.event.pull_request.number }}';
          const targetBranch = '${{ inputs.target_branch }}';

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: `ℹ️ ${targetBranch}ブランチへのチェリーピックをスキップしました。\n\nこの変更は既に${targetBranch}ブランチに含まれているため、チェリーピックの必要がありません。`
          });

    - name: Push branch
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'false'
      shell: bash
      run: |
        NEW_BRANCH="${{ steps.create-branch.outputs.new_branch }}"
        git push origin "${NEW_BRANCH}"
        echo "Pushed branch: ${NEW_BRANCH}"

    - name: Create Pull Request
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'false'
      id: create-pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        SOURCE_BRANCH="${{ steps.create-branch.outputs.source_branch }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        MERGE_COMMIT_SHA="${{ steps.get-merge-commit.outputs.merge_commit_sha }}"
        HAS_CONFLICTS="${{ steps.cherry-pick.outputs.has_conflicts }}"
        TARGET_BRANCH="${{ inputs.target_branch }}"
        TARGET_BRANCH_LABEL="$(echo ${TARGET_BRANCH} | sed 's/^\(.\)/\U\1/')"

        # コンフリクト警告の作成
        CONFLICT_WARNING=""
        if [ "${HAS_CONFLICTS}" = "true" ]; then
          CONFLICT_WARNING=$(cat <<'CONFLICT_EOF'

        ## ⚠️ コンフリクトが発生しました

        このPRにはコンフリクトが含まれています。以下のファイルを確認して、手動で解決してください。

        <details>
        <summary>コンフリクト情報</summary>

        ```
        ${{ steps.cherry-pick.outputs.conflict_info }}
        ```
        </details>

        CONFLICT_EOF
        )
        fi

        # PRの本文を作成
        PR_BODY=$(cat <<EOF
        ### 元のPR
        - #${PR_NUMBER}

        ${CONFLICT_WARNING}

        ### 確認事項
        - [ ] コンフリクトがないことを確認

        ---
        _このPRは GitHub Actions により自動生成されました_
        EOF
        )

<<<<<<< HEAD
        # gh pr createでPRを作成
        PR_URL=$(gh pr create \
          --title "[${TARGET_BRANCH_LABEL}] ${PR_TITLE}" \
=======
        # 元のタイトルから先頭の [] ラベルを削除
        ORIGINAL_TITLE=$(echo "${PR_TITLE}" | sed -E 's/^\[[^]]+\] //')
        
        # gh pr createでPRを作成
        PR_URL=$(gh pr create \
          --title "[${TARGET_BRANCH_LABEL}] ${ORIGINAL_TITLE}" \
>>>>>>> 9be1be4 (Merge pull request #84 from takaaki12353491/chore/auto-pr)
          --body "${PR_BODY}" \
          --base "${TARGET_BRANCH}" \
          --head "${{ steps.create-branch.outputs.new_branch }}")

        echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT
        echo "Pull Request created: ${PR_URL}"

        # PRの番号を抽出
        PR_NUM=$(echo "${PR_URL}" | grep -oE '[0-9]+$')
        echo "pr_number=${PR_NUM}" >> $GITHUB_OUTPUT

    - name: Comment on original PR
      if: steps.cherry-pick.outputs.success == 'true' && steps.cherry-pick.outputs.is_empty == 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = '${{ github.event.pull_request.number }}';
          const newPrNumber = '${{ steps.create-pr.outputs.pr_number }}';
          const hasConflicts = '${{ steps.cherry-pick.outputs.has_conflicts }}' === 'true';
          const targetBranch = '${{ inputs.target_branch }}';

          let message = '';
          if (hasConflicts) {
            message = `⚠️ ${targetBranch}ブランチへのチェリーピックPRが作成されました: #${newPrNumber}\n\n**注意**: コンフリクトが発生しています。PRを確認して手動で解決してください。`;
          } else {
            message = `✅ ${targetBranch}ブランチへのチェリーピックPRが作成されました: #${newPrNumber}`;
          }

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: message
          });

