name: Check frontend general

on:
  push:
    branches-ignore:
      - main
    paths:
      - frontend/general/**
      - .github/workflows/check-frontend-general.yml
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: frontend/general

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Check format
        run: bun run format

      - name: Check lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build
        run: bun run build

      - name: Test
        run: bun test