name: Reusable Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  migration:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_IAM_ROLE_ARN }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.AWS_MIGRATION_ECR_URL }}:latest db/mysql

      - name: Push Docker image to ECR
        run: |
          docker push ${{ vars.AWS_MIGRATION_ECR_URL }}:latest
