name: Reusable Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      tf_version:
        required: false
        type: string
        default: "1.9.5"
      tg_version:
        required: false
        type: string
        default: "0.66.9"

jobs:
  migration:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_IAM_ROLE_ARN }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set IMAGE_TAG
        id: image_tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.AWS_MIGRATION_ECR_URL }}:${{ env.IMAGE_TAG }} db/mysql

      - name: Push Docker image to ECR
        run: |
          docker push ${{ vars.AWS_MIGRATION_ECR_URL }}:${{ env.IMAGE_TAG }}

      - name: Plan migration task
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_dir: "infra/env/stg/operation/migration/"
          tg_command: "plan --target=aws_ecs_task_definition.migration -var=image_tag=${{ env.IMAGE_TAG }}"

      - name: Apply migration task
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_dir: "infra/env/stg/operation/migration/"
          tg_command: "apply --target=aws_ecs_task_definition.migration -var=image_tag=${{ env.IMAGE_TAG }}"
